theme: jekyll-theme-cayman
url: randydeo.com
title: Welcome, my name is Randy Deo
description: and I am a software developer from Trinidad and Tobago.
avatar: "src/images/RD%20Logo%20Black%20NO%20BG.png"
